### ISSUE TITLE
bug on pseudo classes

### ISSUE THREAD

**Issue by ArthurPERE** [olback/es6-css-minify#155]
**Describe the bug**
Hello, I found a bug in the css part, when using pseudo class, all the spaces are removed inside the parenthesis.

**To Reproduce**

Copy and paste this in a css file.
``` css
table :is(tbody tr, thead th) {
  background-color: red;
  margin: 2px;
}
```
And minify it, you will obtain :
``` css
table :is(tbodytr,theadth){background-color:red;margin:2px}
```
the tbody is glued to the tr and the thead is glued to the th.

**Expected behavior**
The behavior I expected is this is the minifyed file :
``` css
table :is(tbody tr,thead th){background-color:red;margin:2px}
```
With, for this example, the tbody and tr with a space between.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Version : 
   - codium version 1.74.2
   - JS & CSS Minifier (Minify) v3.3.3

Regards,
Arthur
